name: ci

on:
  - push

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: create .npmrc
        run: 'echo -e "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN\n@preservetube:registry=https://npm.pkg.github.com/" > .secret_npmrc'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          secret-files: |
            "npmrc=./.secret_npmrc"
          tags: ghcr.io/${{ github.repository }}:latest